_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  block: 0
  config: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  language: 0
  media: 0
  media_library: 0
  mysql: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  system: 0
  text: 0
  token: 0
  user: 0
  pathauto: 1
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable9: 0
  dev_theme: 0
profile: minimal
